name: main
on:
  - pull_request
  - push
jobs:
  main:
    name: ${{matrix.node}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          node-version: ${{matrix.python-version}}
      - run: |
          python -m pip install --upgrade pip pipenv
          pipenv install --dev
      - run: |
          pipenv run pytest
      - run: |
          pipenv run flake8 github_slugger tests
    strategy:
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
